---
title: "PrimerRMD"
author: "Pablo Quesada Peyro"
date: "2024-03-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE}
library(readr)
library(dplyr)

ficheros <- list.files(path = "./data", pattern = ".txt", full.names = TRUE)

lista <- list()

for (fichero in ficheros) {
  r <- read_lines(fichero, locale = locale(encoding = "latin1"))
  r <- r[r != '']
  empresa <- r[1]
  direc <- r[2]
  ciudad <- r[3]
  telefono_r <- r[grep("TELÉFONO:", r)] 
  telefono <- substring(telefono_r, regexpr(":", text = telefono_r) + 1)
  fecha <- r[5]
  if (!is.na(fecha)) {
    partes_fecha_operacion <- strsplit (fecha, " ")
    fecha <- partes_fecha_operacion[[1]][1]
    hora<-partes_fecha_operacion[[1]][2]
    op<-partes_fecha_operacion[[1]][5]
    
    
  } else{
    fecha<-NA
    numero_operacion<-NA
  }
  num_op <- r[6]
  fac <- r[7]
  
  # Encontrar la línea que contiene "TOTAL" utilizando una expresión regular
  total_line_index <- grep("TOTAL \\(", r, ignore.case = TRUE)
  if (length(total_line_index) > 0) {
    productos <- r[8:(total_line_index - 1)]  # Extraer los productos
    df <- data.frame(
      empresa = empresa,
      direccion = direc,
      ciudad = ciudad,
      Telefono = telefono,
      Fecha = fecha,
      Hora = hora,
      numero_operacion = op,
      factura = fac,
      productos = productos,
      stringsAsFactors = FALSE
    )
  } else {
    # Si no se encuentra "TOTAL (?)" establecer productos como NA
    df <- data.frame(
      empresa = empresa,
      direccion = direc,
      ciudad = ciudad,
      Telefono = telefono,
      Fecha = fecha,
      numero_operacion = num_op,
      factura = fac,
      productos = NA,
      stringsAsFactors = FALSE
    )
  }
  
  lista[[length(lista) + 1]] <- df
}

# Combinar todos los data frames en uno solo
datos <- bind_rows(lista)
#datos <- separate(datos, Fecha, into=c("Fecha", "Hora"))
#head(datos)


```
